### ISSUE TITLE
Lỗi    raise child_exception_type(errno_num, err_msg, err_filename)

### ISSUE THREAD

**Issue by nltoan** [v-nhandt21/Vinorm#1]
Dear bạn
Mình đang nghiên cứu sử dụng https://github.com/NoahDrisort/vinorm
Cám ơn bạn vì những đóng góp, bạn cho mình hỏi, sao mình dùng thì toàn bị báo lỗi sau:
 S=TTSnorm("Chuáº©n hÃ³a há» thá»ng nÃ³i tá»± Äá»ng, gá»m RegEx vÃ  Acronyms")
  File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/site-packages/vinorm/__init__.py", line 16, in TTSnorm
    subprocess.check_call([E], env=myenv, cwd=A)
  File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/site-packages/vinorm/main'
Bạn cho mình hỏi cách khắc phục như thế nào được nhỉ

Cám ơn bạn!

**Comment by NoahDrisort** [comment]
> Dear bạn
> Mình đang nghiên cứu sử dụng https://github.com/NoahDrisort/vinorm
> Cám ơn bạn vì những đóng góp, bạn cho mình hỏi, sao mình dùng thì toàn bị báo lỗi sau:
> S=TTSnorm("Chuáº©n hÃ³a há»� thá»�ng nÃ³i tá»± Ä�á»�ng, gá»�m RegEx vÃ  Acronyms")
> File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/site-packages/vinorm/**init**.py", line 16, in TTSnorm
> subprocess.check_call([E], env=myenv, cwd=A)
> File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/subprocess.py", line 306, in check_call
> retcode = call(*popenargs, **kwargs)
> File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/subprocess.py", line 287, in call
> with Popen(*popenargs, **kwargs) as p:
> File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/subprocess.py", line 729, in **init**
> restore_signals, start_new_session)
> File "/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/subprocess.py", line 1364, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> OSError: [Errno 8] Exec format error: '/Users/bubeo/anaconda3/envs/vi2ipa/lib/python3.6/site-packages/vinorm/main'
> Bạn cho mình hỏi cách khắc phục như thế nào được nhỉ
> 
> Cám ơn bạn!

@nltoan à Bạn ơi mình viết package này có sử dụng thư viện ICU: http://userguide.icu-project.org/ để xử lí chuẩn hóa tiếng Việt, và mình dùng bản custom cho Ubuntu 18.04 á. Nên để sử dụng mình phải run trên subsystem hoặc Ubuntu bạn.
Nếu lỗi vẫn xảy ra bạn reply mình nha

**Comment by bubeo** [comment]
Cám ơn bạn
Do mình đang chạy trên macos nên nó toàn lỗi có vẻ không tìm thấy file :(. Chắc phải thử ubtunu vậy

**Comment by nltoan** [comment]
Bạn ơi, cho minh hỏi thêm, để dùng cái này bạn có thể cho mình danh sách các character k nhỉ:(. MÌnh k biết danh sách các character để có thể sử dụng để trainning cho text2speech được!

**Comment by NoahDrisort** [comment]
> Bạn ơi, cho minh hỏi, để dùng cái này bạn có thể cho mình danh sách các character k nhỉ:(. MÌnh k biết danh sách các character để có thể sử dụng để trainning cho text2speech được!

Nếu cho training text2speech và bạn dùng input là các character thì mình nghĩ có 2 lựa chọn:

+Nếu dùng hàm TTSnorm thì letter là : aáảàãạâấẩầẫậăắẳằẵặbcdđeéẻèẽẹêếểềễệfghiíỉìĩịjklmnoóỏòõọôốổồỗộơớởờỡợpqrstuúủùũụưứửừữựvwxyýỷỳỹỵz

+Nếu dùng TTSrawUpper thì bạn thêm các chữ in hoa nữa

Bạn tham khảo thêm các hàm ở pypi: https://pypi.org/project/vinorm/  , do github mình chưa cập nhật hết, 

Với theo mình thấy nếu bạn dùng để train ví dụ như cho tacotron thì bạn có thể lựa chọn hàm TTSnorm_punc_unknown để giữ nguyên các các từ không xác định, để máy tự học.
