### ISSUE TITLE
Lỗi khi sử dụng với XphoneBert_VITs

### ISSUE THREAD

**Issue by manhcuong17072002** [v-nhandt21/Vinorm#11]
Em chào anh ạ. Hiện tại em đang dùng `Vinorm` để chuẩn hóa text dữ liệu đầu vào cho bài toán TTS. Tuy nhiên khi kết hợp `Vinorm` với `XPhoneBert_VITS` thì em đang gặp vấn đề lỗi sau khi chạy lại nhiều lần (lần đầu tiên vẫn chạy được ạ)
```python
[2](vscode-notebook-cell:?execution_count=15&line=2) from vinorm import TTSnorm
      [4](vscode-notebook-cell:?execution_count=15&line=4) text = "Xin chào, mình là Cường. Mình năm nay hai mươi ba tuổi. Mình ở Hà Nội. Mình rất vui khi được gặp bạn."
----> [5](vscode-notebook-cell:?execution_count=15&line=5) norm_text = TTSnorm(text)
      [6](vscode-notebook-cell:?execution_count=15&line=6) text_segment = word_tokenize(norm_text, format="text")
      [7](vscode-notebook-cell:?execution_count=15&line=7) _ = utils.load_checkpoint("logs/infore_25h_p2//G_68000.pth", net_g, None)

File [~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:10](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:10), in TTSnorm(text, punc, unknown, lower, rule)
      [8](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:8) I=A+"[/input.txt](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/input.txt)"
      [9](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:9) with open(I,"w+") as fw:
---> [10](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:10)     fw.write(text)
     [12](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:12) myenv = os.environ.copy()
     [13](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:13) myenv['LD_LIBRARY_PATH'] = A+'[/lib](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/lib)'

UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 6: ordinal not in range(128)
```
Em không biết lỗi này do đâu và em cũng nghĩ phần này do câu lệnh `with open(I,"w+") as fw:` thiếu tham số `encoding = "utf-8"`. Anh có thể cho em xin ý kiến về vấn đề này được không ạ. Em xin cảm ơn ạ

**Comment by v-nhandt21** [comment]
> Em chào anh ạ. Hiện tại em đang dùng `Vinorm` để chuẩn hóa text dữ liệu đầu vào cho bài toán TTS. Tuy nhiên khi kết hợp `Vinorm` với `XPhoneBert_VITS` thì em đang gặp vấn đề lỗi sau khi chạy lại nhiều lần (lần đầu tiên vẫn chạy được ạ)
> 
> ```python
> [2](vscode-notebook-cell:?execution_count=15&line=2) from vinorm import TTSnorm
>       [4](vscode-notebook-cell:?execution_count=15&line=4) text = "Xin chào, mình là Cường. Mình năm nay hai mươi ba tuổi. Mình ở Hà Nội. Mình rất vui khi được gặp bạn."
> ----> [5](vscode-notebook-cell:?execution_count=15&line=5) norm_text = TTSnorm(text)
>       [6](vscode-notebook-cell:?execution_count=15&line=6) text_segment = word_tokenize(norm_text, format="text")
>       [7](vscode-notebook-cell:?execution_count=15&line=7) _ = utils.load_checkpoint("logs/infore_25h_p2//G_68000.pth", net_g, None)
> 
> File [~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:10](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:10), in TTSnorm(text, punc, unknown, lower, rule)
>       [8](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:8) I=A+"[/input.txt](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/input.txt)"
>       [9](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:9) with open(I,"w+") as fw:
> ---> [10](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:10)     fw.write(text)
>      [12](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:12) myenv = os.environ.copy()
>      [13](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/home/misa-cv/nmcuong/VITS_with_XPhoneBERT/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py:13) myenv['LD_LIBRARY_PATH'] = A+'[/lib](https://vscode-remote+ssh-002dremote-002bgpu-002dmisa.vscode-resource.vscode-cdn.net/lib)'
> 
> UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 6: ordinal not in range(128)
> ```
> 
> Em không biết lỗi này do đâu và em cũng nghĩ phần này do câu lệnh `with open(I,"w+") as fw:` thiếu tham số `encoding = "utf-8"`. Anh có thể cho em xin ý kiến về vấn đề này được không ạ. Em xin cảm ơn ạ

Anh nghĩ chắc do thiếu encoding = "utf-8" thiệt á, em xem sửa thẳng trực tiếp ở lib file "/~/miniconda3/envs/text2speech/lib/python3.10/site-packages/vinorm/__init__.py" coi còn bị không hén :))

**Comment by manhcuong17072002** [comment]
@v-nhandt21 Liệu em git clone về rồi chỉnh sửa thì có dùng trực tiếp được không ạ. Vì em thấy hiện tại chỉ hỗ trợ cho linux với mac nên em sợ phải build những thứ khác liên quan tới hệ điều hành ạ. Em đang dùng remote tới server ạ.

**Comment by manhcuong17072002** [comment]
> Liệu em git clone về rồi chỉnh sửa thì có dùng trực tiếp được không ạ

Em thử git clone về và đã chạy được ạ. Tuy nhiên em không cần phải thêm `encoding = "utf-8"` vào `with open(I,"w+") as fw:` và phải build bất cứ gì để chạy ạ. Em xin cảm ơn anh

**Comment by v-nhandt21** [comment]
> > Liệu em git clone về rồi chỉnh sửa thì có dùng trực tiếp được không ạ
> 
> 
> 
> Em thử git clone về và đã chạy được ạ. Tuy nhiên em không cần phải thêm `encoding = "utf-8"` vào `with open(I,"w+") as fw:` và phải build bất cứ gì để chạy ạ. Em xin cảm ơn anh

À sửa trực tiếp luôn á em, nó như một file python nhưng nằm ở path conda thôi
