### ISSUE TITLE
Update version for main

### ISSUE THREAD

**Issue by v-nhandt21** [v-nhandt21/Vinorm#3]
In this version, do not replace unknow words, skip them for espeak handle in phonetization step:

Replace "main" with this file: 
[main.zip](https://github.com/NoahDrisort/vinorm/files/5731478/main.zip)

**Comment by NoahDrisort** [comment]
This version does not parse case:  "Tổ chức WTO"
WTO do not in dictionary -> unknow -> keep origin, do not spell as in version 1.0, this aim to use with espeak, let espeak handle, but the drawback is the output of espeak for this case is "ve1kɛɜpte1ɔ7", it does not split each syllable.
For new entity, need to update in the dictionary
