### ISSUE TITLE
How to use this package on Windows (11)?

### ISSUE THREAD

**Issue by princ3od** [v-nhandt21/Vinorm#4]
Hi Nhan,
Seem like the `cpp` main file is built for Linux only. Could you please provide the version that can run on Windows? I tried to direct to `vinorm_cpp_version` to be able to build it myself but had no luck. 😥
Looking forward to hearing from you soon.
Thanks,

**Comment by v-nhandt21** [comment]
Hi @princ3od, this library was built based on ICU library, and this version support running on Linux only, you can try to use linux subsystem or VMWare :))

Maybe in the future I would update the version for window, currently I have a Vinorm version which running in Android amd using NDK, if you are interested, I would add you to my current project.

**Comment by princ3od** [comment]
Hey @v-nhandt21,
Thanks for your response. 

> Hi @princ3od, this library was built based on ICU library, and this version support running on Linux only, you can try to use linux subsystem or VMWare :))

Nice suggestion! I'll surely do it while waiting for your Windows version.✌️

> Maybe in the future I would update the version for window, currently I have a Vinorm version which running in Android amd using NDK, if you are interested, I would add you to my current project.

Oh, It would be my honor to be a part of your project. I also have my own "Vinorm" using only regex in Python, but still looking to if there is any better solution. So far I have only found your precious repo.

**Comment by v-nhandt21** [comment]
> Hey @v-nhandt21, Thanks for your response.
> 
> > Hi @princ3od, this library was built based on ICU library, and this version support running on Linux only, you can try to use linux subsystem or VMWare :))
> 
> Nice suggestion! I'll surely do it while waiting for your Windows version.v
> 
> > Maybe in the future I would update the version for window, currently I have a Vinorm version which running in Android amd using NDK, if you are interested, I would add you to my current project.
> 
> Oh, It would be my honor to be a part of your project. I also have my own "Vinorm" using only regex in Python, but still looking to if there is any better solution. So far I have only found your precious repo.

Sorry for my late reply, I have added you to the android project, If you are interested, you can refactor it and we would release it public someday :)) . My current research is not related to norm, so I can't maintain it more.
