### ISSUE TITLE
OSError when running vinorm on MacOS 

### ISSUE THREAD

**Issue by duongttr** [v-nhandt21/Vinorm#7]
Hello,
I faced this issue without understanding why it was running on Google Colab but not on my local MacBook:
`OSError: [Errno 8] Exec format error: '/Users/jaydentran1909/miniconda3/envs/zac/lib/python3.7/site-packages/vinorm/main'`

Is this library for only Linux-kernel? If it is, is there any solution for running on MacOS?

Thank you very much!

**Comment by v-nhandt21** [comment]
Yes, This repo only supports deployment in Linux only, You can try on colab or a Linux server and get the normalized text for the next processing stage.
